# springboot2.0默认数据源配置HikariDataSource
#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/southweb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver

# 数据源改成Druid
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/southweb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #数据源其他配置(可选),默认DataSourceProperties中并无下面这些参数。需要新建配置类DruidConfig
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    #每隔10分钟把监控数据输出到日志中
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


